### ISSUE TITLE
Support for constraints file?

### ISSUE THREAD

**Issue by chris-x86-64** [pyupio/safety#135] opened 2018-06-25 05:59 UTC
* safety version: 1.8.1 (latest at the moment)
* Python version: 3.6.2
* Operating System: Debian 8 (Docker container)

### Description

This is a feature suggestion.
My project has a constraints file (i.e. `constraints.txt`) which pins the libraries' versions.
I was wondering if there's a plan to support constraints, e.g.
```
safety check -r requirements.txt -c constraints.txt
```

### What I Did

In the meantime, I'm working it around by actually installing the requirements and then running _safety_ with stdin mode:
```shell
pip install -r requirements.txt -c constraints.txt 
pip freeze | safety check --stdin
```

Nice project. Cheers!

**Comment by rafaelpivato** [comment] 2020-03-23 21:16
This sounds indeed like a great idea. Good to know you did find a workaround! :tada:

**Comment by stevecj** [comment] 2020-05-08 19:38
Installing the requirements is an awkward workaround when there are both development and production packages. Development dependencies are generally included in the frozen constraints.txt, even though they do not need to be checked.

Ideally, packages to scan would be determined by following the dependency tree from packages in requirements.txt, then versions of those would be determined from the frozen constraints file.

In order for the dependency tree to be deterministic, I think that either all of the packages in that tree need to be installed and match frozen versions in the constraints file (which is fine with me) or after each package is identified, its version is immediately resolved using the constraints (prior to trying to descend into that package's sub-dependencies).

**Comment by dylanpulver** [comment] 2024-07-23 19:23
duplicate of https://github.com/pyupio/safety/issues/507

**Closed** 2024-12-19 00:47 UTC
Labels: enhancement, considering
