### ISSUE TITLE
support shell globs with a new command that takes multiple file options

### ISSUE THREAD

**Issue by graingert** [pyupio/safety#306] opened 2020-06-22 15:07 UTC
* safety version: NA
* Python version: NA
* Operating System: NA

### Description

I'm trying to run `safety check -r **/requirements*.txt` but `-r` only allows one command

introduce a new command that supports unixy `[FILE...]`
`safety check_requirements [OPTION...] [FILE...]`

**Comment by lf1up** [comment] 2020-06-23 04:47
@graingert thank you for this case. You are right, at this moment `-r` allows only one file per option. You need to use `-r` option multiple times if you want to pass more files (https://click.palletsprojects.com/en/7.x/options/#multiple-options). There is no `[FILE...]` support due to the `click` library limitations (we are using this library to parse command line args: https://github.com/pallets/click/issues/484). I added this to our list of upcoming features and bugfixes.

Meanwhile, you can try with this quick workaround: `for f in **/requirements*.txt; do safety check -r "$f"; done`

**Comment by graingert** [comment] 2020-06-23 10:48
@lf1up https://click.palletsprojects.com/en/7.x/arguments/#variadic-arguments it looks like you can pass `nargs=-1` now

**Comment by lf1up** [comment] 2020-06-23 10:57
@graingert at this moment we are using `@click.option` almost everywhere. Possible usage of `@click.argument` should be considered and tested, because it is not an equivalent (drop-in) replacement.

**Comment by filonik** [comment] 2022-11-15 11:24
Just wanted to echo the desire to support variadic options. My use case also involves using shell globs/wildcards within options. I think the `OptionEatAll` solution on StackOverflow gets the expected behavior right:

https://stackoverflow.com/questions/48391777/nargs-equivalent-for-options-in-click

Although this is a workable solution, but it would be nice to have it supported in the library directly. It feels like quite a natural feature, especially considering variadic arguments.

**Comment by dylanpulver** [comment] 2024-07-24 20:58
Hi @graingert,

Thank you for your suggestion and for highlighting this use case.

After careful consideration, we've decided to move this issue to the "wontfix" category. We wanted to provide some context for our decision:

Existing Support: While we understand the desire for a new command to support shell globs and multiple file options, this functionality is already supported in the safety scan command. We recommend using safety scan to handle such cases effectively.

We appreciate your understanding and encourage you to try the safety scan command for your use case. If you have any further suggestions or feedback, we would love to hear from you.

Thank you for your continued support and contributions!

Best regards,

The Safety Team

**Closed by dylanpulver** 2024-07-24 20:58 UTC
Labels: enhancement, considering
