### ISSUE TITLE
safety-schemas 0.0.7 requires outdated pydantic version that fails install on Python 3.13

### ISSUE THREAD

**Issue by andy-maier** [pyupio/safety#620] opened 2024-10-24 09:48 UTC
### Checklist

- [X] I agree to the terms within the [Safety Code of Conduct](https://github.com/pyupio/safety/blob/main/CODE_OF_CONDUCT.md).

### Safety version

safety-schemas 0.0.7

### Python version

3.13

### Operating System

macos, Ubuntu, Windows

### Describe the problem you'd like to have solved

I am using the safety issue tracker for reporting this issue of safety-schemas, because I'm not aware of an issue tracker for safety-schemas.

The safety-schemas package version 0.0.7 has the following package dependencies:
```
$ python -m pipdeptree -p safety-schemas
safety-schemas==0.0.7
├── dparse [required: >=0.6.4b0, installed: 0.6.4b0]
│   └── packaging [required: Any, installed: 24.1]
├── packaging [required: >=21.0, installed: 24.1]
├── pydantic [required: ~=2.5.0, installed: 2.5.3]
│   ├── annotated-types [required: >=0.4.0, installed: 0.7.0]
│   ├── pydantic_core [required: ==2.14.6, installed: 2.14.6]
│   │   └── typing_extensions [required: >=4.6.0,!=4.7.0, installed: 4.12.2]
│   └── typing_extensions [required: >=4.6.1, installed: 4.12.2]
├── ruamel.yaml [required: >=0.17.21, installed: 0.18.6]
│   └── ruamel.yaml.clib [required: >=0.2.7, installed: 0.2.12]
└── typing_extensions [required: >=4.7.1, installed: 4.12.2]
```

This dependency chain pulls in pydantic-core 2.14.6 and which has a bug that causes its installation to fail on Python 3.13.
That bug has been reported in https://github.com/pydantic/pydantic-core/issues/1366 and again in https://github.com/pydantic/pydantic-core/issues/1500 and has been fixed with https://github.com/pydantic/pydantic-core/pull/1299 in pydantic-core version 2.18.3.

pydantic-core version 2.18.3 was for the first time pulled in by pydantic version 2.7.2.

However, pydantic 2.7.2 has other install issues on Python 3.13, and I found that I needed pydantic>=2.8.0 to successfully install on Python 3.13.

Note that pydantic and pydantic-core are very tightly coupled in their dependencies: pydantic specifies the exact and only version of pydantic-core to be used.

The current dependency safety-schemas 0.0.7 specifies for the pydantic package is `~=2.5.0` which uses the so-called compatibility operator `~=` which is equivalent to `>=2.5.0, <2.6.0`. This prevents installing the version of pydantic that has the bug fix.

safety-schemas 0.0.5 allowed any version for the pydantic package; That's why this issue started to occur with the release of safety-schemas 0.0.7.

### Describe the ideal solution

Do not specify an upper limit for the pydantic dependency, at least not an upper 2.x minor version.

Specifying `pydantic ~= 2.5` might be ok, because that is equivalent to `>=2.5.0, <3.0.0`

### Alternatives and current workarounds

Our circumvention is to exclude safety-schemas 0.0.7, hoping that a subsequent safety-schemas version will no longer pin pydantic to <2.6.0.

### What I Did

On Python 3.13:
```
pip install safety
```

**Comment by Dresdn** [comment] 2024-11-22 15:33
I didn't want to open a new ticket, so I'm piggybacking here since the core issue is the same.

Can we revisit the decision to enforce an upper bound on the Pydantic version at the minor level @SafetyQuincyF @dylanpulver? With `safety-schemas` v0.0.9 (released Nov 4), the dependency is currently specified as "pydantic>=2.6.0,<2.10.0". However, Pydantic has since released versions 2.10.0 and 2.10.1, and this strict pinning is unnecessarily blocking the use of newer versions and their fixes/features.

Can we consider loosening the dependency to allow for major version compatibility instead, e.g., `pydantic>=2.6.0,<3.0.0`? This would be a much more sustainable and developer-friendly approach.

**Comment by SafetyQuincyF** [comment] 2024-12-19 02:06
Hi @andy-maier,

Thank you once again for reporting this issue! I’m happy to share that it has been resolved in the latest version of the Safety schema. I’ve tested it on Python 3.13, and everything is working as intended. 🎉

Let me know if you encounter any further issues!

**Closed by SafetyQuincyF** 2024-12-19 02:06 UTC

**Comment by alex-pobeditel-2004** [comment] 2024-12-25 15:40
@SafetyQuincyF hello! Are there any inconsistencies with `pydantic >= 2.10.0`?   
It was released one month ago and Safety is incompatible with it 🤔

**Comment by andy-maier** [comment] 2025-01-05 12:56
@SafetyQuincyF Thanks for the fix - it works for us.

I agree however with @alex-pobeditel-2004 that pinning pydantic to <2.10.0 is not a good idea. Sooner or later some package will require pydantic versions that are in conflict with that, so why do you create such a time bomb? Of course, unless there is a good reason, but it is not clear what that reason would be.
